[project]
name = "proj-sqld"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = [
    "pandas>=2.2.3",
    "playwright>=1.52.0",
    "tabulate>=0.9.0",
]
